import Foundation

public enum MockData {
    public static let user = GitHubUser(login: "mattnz", name: "Matt Connors", avatarHue: 80)

    public static var rateLimit: RateLimit {
        RateLimit(limit: 5_000, remaining: 4_832, resetAt: Date().addingTimeInterval(47 * 60))
    }

    public static var runs: [WorkflowRun] {
        let now = Date()
        func ago(_ s: TimeInterval) -> Date { now.addingTimeInterval(-s) }
        let urlBase = URL(string: "https://github.com")!

        return [
            .init(id: 1, repo: "mattnz/orbital-cms", workflowName: "CI",
                  displayTitle: "Strip trailing whitespace in markdown frontmatter",
                  branch: "main", event: "push",
                  status: .inProgress, conclusion: nil, runNumber: 1842,
                  actor: "mattnz", actorHue: 80,
                  startedAt: ago(134), updatedAt: now, durationSeconds: 134,
                  htmlURL: urlBase.appending(path: "mattnz/orbital-cms/actions/runs/1842")),
            .init(id: 2, repo: "mattnz/orbital-cms", workflowName: "Deploy · staging",
                  displayTitle: "Strip trailing whitespace in markdown frontmatter",
                  branch: "main", event: "push",
                  status: .queued, conclusion: nil, runNumber: 1842,
                  actor: "mattnz", actorHue: 80,
                  startedAt: ago(20), updatedAt: now, durationSeconds: 0,
                  htmlURL: urlBase.appending(path: "mattnz/orbital-cms/actions/runs/1843")),
            .init(id: 3, repo: "kintsugi-labs/spindle", workflowName: "Release",
                  displayTitle: "v3.4.0 — segmenter perf, fix split-on-emoji",
                  branch: "release/3.4", event: "workflow_dispatch",
                  status: .completed, conclusion: .failure, runNumber: 412,
                  actor: "rinapeters", actorHue: 25,
                  startedAt: ago(14 * 60), updatedAt: ago(14 * 60 - 348), durationSeconds: 348,
                  htmlURL: urlBase.appending(path: "kintsugi-labs/spindle/actions/runs/412")),
            .init(id: 4, repo: "kintsugi-labs/spindle", workflowName: "CI",
                  displayTitle: "feat(parser): lookahead for compound tokens",
                  branch: "rina/parser-lookahead", event: "pull_request",
                  status: .completed, conclusion: .success, runNumber: 1109,
                  actor: "rinapeters", actorHue: 25,
                  startedAt: ago(22 * 60), updatedAt: ago(22 * 60 - 192), durationSeconds: 192,
                  htmlURL: urlBase.appending(path: "kintsugi-labs/spindle/actions/runs/1109")),
            .init(id: 5, repo: "mattnz/dotfiles", workflowName: "Lint",
                  displayTitle: "chore: bump fish to 4.2",
                  branch: "main", event: "push",
                  status: .completed, conclusion: .success, runNumber: 87,
                  actor: "mattnz", actorHue: 80,
                  startedAt: ago(38 * 60), updatedAt: ago(38 * 60 - 41), durationSeconds: 41,
                  htmlURL: urlBase.appending(path: "mattnz/dotfiles/actions/runs/87")),
            .init(id: 6, repo: "foundry-co/relay", workflowName: "CI",
                  displayTitle: "Reduce p99 latency on /v2/dispatch",
                  branch: "perf/dispatch-p99", event: "pull_request",
                  status: .completed, conclusion: .success, runNumber: 9438,
                  actor: "jpark", actorHue: 200,
                  startedAt: ago(60 * 60), updatedAt: ago(60 * 60 - 483), durationSeconds: 483,
                  htmlURL: urlBase.appending(path: "foundry-co/relay/actions/runs/9438")),
            .init(id: 7, repo: "foundry-co/relay", workflowName: "Nightly · integration",
                  displayTitle: "scheduled · 02:00 UTC",
                  branch: "main", event: "schedule",
                  status: .completed, conclusion: .failure, runNumber: 612,
                  actor: "foundry-bot", actorHue: 150,
                  startedAt: ago(3 * 60 * 60), updatedAt: ago(3 * 60 * 60 - 862), durationSeconds: 862,
                  htmlURL: urlBase.appending(path: "foundry-co/relay/actions/runs/612")),
            .init(id: 8, repo: "foundry-co/relay-edge", workflowName: "CI",
                  displayTitle: "Drop libpcap dep on macOS arm64",
                  branch: "main", event: "push",
                  status: .completed, conclusion: .success, runNumber: 2201,
                  actor: "jpark", actorHue: 200,
                  startedAt: ago(4 * 60 * 60), updatedAt: ago(4 * 60 * 60 - 175), durationSeconds: 175,
                  htmlURL: urlBase.appending(path: "foundry-co/relay-edge/actions/runs/2201")),
            .init(id: 9, repo: "mattnz/almanac", workflowName: "Build site",
                  displayTitle: "Add 2026 lunar calendar overlay",
                  branch: "feat/lunar-2026", event: "pull_request",
                  status: .completed, conclusion: .success, runNumber: 304,
                  actor: "mattnz", actorHue: 80,
                  startedAt: ago(6 * 60 * 60), updatedAt: ago(6 * 60 * 60 - 69), durationSeconds: 69,
                  htmlURL: urlBase.appending(path: "mattnz/almanac/actions/runs/304")),
            .init(id: 10, repo: "kintsugi-labs/spindle-rs", workflowName: "CI",
                  displayTitle: "Bump regex to 1.11; drop once_cell",
                  branch: "main", event: "push",
                  status: .completed, conclusion: .success, runNumber: 558,
                  actor: "rinapeters", actorHue: 25,
                  startedAt: ago(8 * 60 * 60), updatedAt: ago(8 * 60 * 60 - 277), durationSeconds: 277,
                  htmlURL: urlBase.appending(path: "kintsugi-labs/spindle-rs/actions/runs/558")),
            .init(id: 11, repo: "foundry-co/dashboard", workflowName: "Preview deploy",
                  displayTitle: "Onboarding rev 4 · empty states",
                  branch: "eli/onboarding-rev4", event: "pull_request",
                  status: .completed, conclusion: .cancelled, runNumber: 1773,
                  actor: "eliboard", actorHue: 320,
                  startedAt: ago(10 * 60 * 60), updatedAt: ago(10 * 60 * 60 - 32), durationSeconds: 32,
                  htmlURL: urlBase.appending(path: "foundry-co/dashboard/actions/runs/1773")),
            .init(id: 12, repo: "foundry-co/dashboard", workflowName: "CI",
                  displayTitle: "Onboarding rev 4 · empty states",
                  branch: "eli/onboarding-rev4", event: "pull_request",
                  status: .completed, conclusion: .success, runNumber: 1772,
                  actor: "eliboard", actorHue: 320,
                  startedAt: ago(10 * 60 * 60), updatedAt: ago(10 * 60 * 60 - 378), durationSeconds: 378,
                  htmlURL: urlBase.appending(path: "foundry-co/dashboard/actions/runs/1772")),
            .init(id: 13, repo: "mattnz/sprocket", workflowName: "CI",
                  displayTitle: "WIP: device flow polling backoff",
                  branch: "auth/device-flow", event: "push",
                  status: .completed, conclusion: .actionRequired, runNumber: 12,
                  actor: "mattnz", actorHue: 80,
                  startedAt: ago(12 * 60 * 60), updatedAt: ago(12 * 60 * 60 - 22), durationSeconds: 22,
                  htmlURL: urlBase.appending(path: "mattnz/sprocket/actions/runs/12")),
            .init(id: 14, repo: "kintsugi-labs/atlas", workflowName: "Docs",
                  displayTitle: "Rewrite tokenizer chapter for v3",
                  branch: "docs/tokenizer-v3", event: "pull_request",
                  status: .completed, conclusion: .success, runNumber: 88,
                  actor: "rinapeters", actorHue: 25,
                  startedAt: ago(14 * 60 * 60), updatedAt: ago(14 * 60 * 60 - 58), durationSeconds: 58,
                  htmlURL: urlBase.appending(path: "kintsugi-labs/atlas/actions/runs/88")),
            .init(id: 15, repo: "foundry-co/relay", workflowName: "CodeQL",
                  displayTitle: "security scan · weekly",
                  branch: "main", event: "schedule",
                  status: .completed, conclusion: .success, runNumber: 41,
                  actor: "foundry-bot", actorHue: 150,
                  startedAt: ago(24 * 60 * 60), updatedAt: ago(24 * 60 * 60 - 662), durationSeconds: 662,
                  htmlURL: urlBase.appending(path: "foundry-co/relay/actions/runs/41")),
        ]
    }

    public static var repositories: [Repository] {
        [
            .init(id: 1,  fullName: "mattnz/orbital-cms",         org: "Personal",       isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 2,  fullName: "mattnz/dotfiles",            org: "Personal",       isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 3,  fullName: "mattnz/almanac",             org: "Personal",       isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 4,  fullName: "mattnz/sprocket",            org: "Personal",       isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 5,  fullName: "mattnz/old-blog",            org: "Personal",       isArchived: true,  isFork: false, watching: false, muted: true),
            .init(id: 6,  fullName: "kintsugi-labs/spindle",      org: "kintsugi-labs",  isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 7,  fullName: "kintsugi-labs/atlas",        org: "kintsugi-labs",  isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 8,  fullName: "kintsugi-labs/spindle-rs",   org: "kintsugi-labs",  isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 9,  fullName: "foundry-co/relay",           org: "foundry-co",     isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 10, fullName: "foundry-co/dashboard",       org: "foundry-co",     isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 11, fullName: "foundry-co/relay-edge",      org: "foundry-co",     isArchived: false, isFork: false, watching: true,  muted: false),
            .init(id: 12, fullName: "foundry-co/internal-tools",  org: "foundry-co",     isArchived: false, isFork: false, watching: false, muted: true),
        ]
    }
}
